name: Deploy Frontend

on:
  push:
    branches:
      - production

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          VITE_API_URL: https://zenit-backend-991692159165.europe-west1.run.app
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: zenitcloudproject.firebaseapp.com
          VITE_FIREBASE_PROJECT_ID: zenitcloudproject
          VITE_FIREBASE_STORAGE_BUCKET: zenitcloudproject.firebasestorage.app
          VITE_FIREBASE_MESSAGING_SENDER_ID: 991692159165
          VITE_FIREBASE_APP_ID: 1:991692159165:web:18f8f78aba5f1115b65fd4

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.GCP_SA_KEY }}
          projectId: zenitcloudproject
          entryPoint: .